# Generated by Django 5.2.17 on 2026-09-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Realisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="realisations/",
                        verbose_name="image",
                    ),
                ),
                (
                    "site_reference",
                    models.CharField(
                        help_text="Ex : Beta Samati, Gedi, Mogadishu, Aksum",
                        max_length=200,
                        verbose_name="site de référence",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("site", "Site archéologique"),
                            ("city", "Ville d'Afrique de l'Est"),
                        ],
                        default="site",
                        max_length=10,
                        verbose_name="catégorie",
                    ),
                ),
                (
                    "period_label",
                    models.CharField(
                        blank=True,
                        help_text="Ex : ~1950, IVe siècle",
                        max_length=100,
                        verbose_name="période",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
            ],
            options={
                "verbose_name": "réalisation",
                "verbose_name_plural": "réalisations",
                "ordering": ["-created_at"],
            },
        ),
    ]
