# Generated by Django 5.2.17 on 2026-09-28 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='video',
            field=models.FileField(blank=True, help_text="Flyover ou immersion 3D exportée d'Unreal Engine (mp4/webm/mov).", null=True, upload_to='realisations/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov'])], verbose_name='vidéo'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='image',
            field=models.ImageField(blank=True, help_text="Utilisée comme vignette, et comme image d'affiche (poster) si une vidéo est fournie.", null=True, upload_to='realisations/', verbose_name='image / affiche'),
        ),
    ]
