# Generated by Django 5.2.17 on 2026-09-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisations', '0002_realisation_video_alter_realisation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='description_en',
            field=models.TextField(blank=True, help_text='Laisser vide pour afficher la description française par défaut.', verbose_name='description (anglais)'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='description_sw',
            field=models.TextField(blank=True, help_text='Laisser vide pour afficher la description française par défaut.', verbose_name='description (swahili)'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='title_en',
            field=models.CharField(blank=True, help_text='Laisser vide pour afficher le titre français par défaut.', max_length=200, verbose_name='titre (anglais)'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='title_sw',
            field=models.CharField(blank=True, help_text='Laisser vide pour afficher le titre français par défaut.', max_length=200, verbose_name='titre (swahili)'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='description',
            field=models.TextField(verbose_name='description (français)'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titre (français)'),
        ),
    ]
