# Generated by Django 5.2.17 on 2026-09-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatbotRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100, verbose_name="mot-clé")),
                ("answer", models.TextField(verbose_name="réponse")),
            ],
            options={
                "verbose_name": "règle chatbot",
                "verbose_name_plural": "règles chatbot",
            },
        ),
    ]
