# Generated by Django 5.2.17 on 2026-09-21 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=200, verbose_name="nom du client"),
                ),
                (
                    "client_email",
                    models.EmailField(max_length=254, verbose_name="email du client"),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="organisation"
                    ),
                ),
                (
                    "project_description",
                    models.TextField(verbose_name="description du projet"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminée"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créée le"),
                ),
                (
                    "last_reminder_sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="dernière relance envoyée le",
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande",
                "verbose_name_plural": "demandes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_name", models.CharField(max_length=200, verbose_name="étape")),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="terminée"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="terminée le"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="servicerequests.servicerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "étape",
                "verbose_name_plural": "étapes",
                "ordering": ["order"],
            },
        ),
    ]
